name: gcp
channels:
  - anaconda
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - aiohttp
  - aiosignal
  - async-timeout
  - attrs
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - colorlog
  - cryptography
  - frozenlist
  - google-api-core
  - google-auth
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - grpcio
  - idna
  - iniconfig
  - ld_impl_linux-64
  - libabseil
  - libcrc32c
  - libffi
  - libgcc-ng
  - libgomp
  - libgrpc
  - libnsl
  - libprotobuf
  - libsqlite
  - libstdcxx-ng
  - libuuid
  - libzlib
  - multidict
  - ncurses
  - openssl
  - packaging
  - pip
  - pluggy
  - protobuf
  - py
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyopenssl
  - pysocks
  - pytest
  - python
  - python_abi
  - pyu2f
  - re2
  - readline
  - requests
  - rsa
  - setuptools
  - six
  - tk
  - tomli
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yarl
