name: Authenticate google cloud

on: push

jobs:
  GitHub-Tests:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/863040563308/locations/global/workloadIdentityPools/otd-app'
        service_account: 'otd-app@otd-ml.iam.gserviceaccount.com'    

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |     
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run test
      run: |
        pytest tests/test_*.py